theme: jekyll-theme-cayman
title:  Prof. Thaynara Arielly de Lima 
description: Assistant Professor / Universidade Federal de Goiás <a href="Publications.md">Publications</a> 
#<img src="drawing.jpg" alt="drawing" width="200"/>
