theme: jekyll-theme-cayman
subtitle: Prof. Thaynara Arielly de Lima (aka: anginho, mamita, gatinha)
#description: Assistant Professor / Universidade Federal de Goiás
#<img src="drawing.jpg" alt="drawing" width="200"/>
