theme: jekyll-theme-cayman
subtitle: Prof. Thaynara Arielly de Lima
<a href="#Publications">Publications</a> <a href="#Teaching">Teaching</a> <a href="#Teaching">Teaching</a>
#description: Assistant Professor / Universidade Federal de Goiás
#<img src="drawing.jpg" alt="drawing" width="200"/>
