theme: jekyll-theme-cayman
title:  Prof. Thaynara Arielly de Lima 
description: Assistant Professor / Universidade Federal de Goiás ![Publications](Publications.md) 
#<img src="drawing.jpg" alt="drawing" width="200"/>
