theme: jekyll-theme-cayman
<a href="#Publications">Publications</a> <a href="#Teaching">Teaching</a> <a href="#Teaching">Teaching</a>
#title: Thaynara Arielly de Lima
#description: Assistant Professor / Universidade Federal de Goiás
#<img src="drawing.jpg" alt="drawing" width="200"/>
