theme: jekyll-theme-cayman
layout: default
#title:  Prof. Thaynara Arielly de Lima 
description: Assistant Professor / Universidade Federal de Goiás
#<img src="drawing.jpg" alt="drawing" width="200"/>
